### ISSUE TITLE
Параметры расы

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/MUD-GAME#4]
Для каждой расы есть набор параметров - сила, мудрость, ловкость, интеллект. Необходимо написать функцию, которая для заданной расы будет возвращать набор соответствующих параметров.

**Comment by dissod** [comment]
@denyszamiatin 
Есть предложение. параметры сила, мудрость, ловкость, интеллект не позволят в равной степени рассчитывать урон (конечно же, можно рассчитывать коэфициент от силы, но в случае вычисления негативных эффектов (временных) таких как ослабление урона или дебаф на силу - то будет падать и сила и здоровье. 
Предложение - статы сила, выносливость,  ловкость, интеллект
сила - коефициант количества урона (урон = (сила + урон оружия в диапазоне) - защита цели)
выносливость = количество здоровья и коэфициент сопротивления(сопротивление а/10 = коефициэент, 10 выносливости дает 1 % сопротивления) от значения (защита цели = броня+%сопротивления)
