### ISSUE TITLE
Типы профессий

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/MUD-GAME#8]
В вики проекта необходима страница со списком профессий (воин, маг, ...) и их особенностей

**Comment by Nuzhyn-Ivan** [comment]
https://github.com/denyszamiatin/MUD-GAME/wiki/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B-(%D0%BF%D1%80%D0%BE%D1%84%D0%B5%D1%81%D1%81%D0%B8%D0%B8)

**Comment by Nuzhyn-Ivan** [comment]
Edited after @dissod review
